# Generated by Django 3.1.5 on 2021-05-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookadvisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertest',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
